# Generated by Django 3.1.4 on 2020-12-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.FloatField()),
                ('B', models.FloatField()),
                ('C', models.FloatField()),
                ('D', models.FloatField()),
                ('E', models.FloatField()),
                ('F', models.FloatField()),
                ('G', models.FloatField()),
                ('H', models.FloatField()),
                ('I', models.FloatField()),
                ('J', models.FloatField()),
                ('K', models.FloatField()),
                ('L', models.FloatField()),
                ('M', models.FloatField()),
            ],
        ),
    ]
